server:
    servlet:
        context-path: /management-car-rental/api
        
spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
    
springdoc:
  swagger-ui:
    path: /swagger

  h2:
    console:
      enabled: true
      path: /h2-console 

      
