server:
    servlet:
        context-path: /management-car-rental/api
   
springdoc:
  swagger-ui:
    path: /swagger

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental_car?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
